// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfSbOeX5HwdNTVnD7bT67KrBBs5ydDA1s',
    appId: '1:458692017479:web:470aa40f8b0fdc2158a062',
    messagingSenderId: '458692017479',
    projectId: 'seefochat-25003',
    authDomain: 'seefochat-25003.firebaseapp.com',
    storageBucket: 'seefochat-25003.appspot.com',
    measurementId: 'G-JN89JPMBZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3kafPxNoNYoTCNEvFDG8ys9I2pKWlIJw',
    appId: '1:458692017479:android:694570c29c8c91ad58a062',
    messagingSenderId: '458692017479',
    projectId: 'seefochat-25003',
    storageBucket: 'seefochat-25003.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvCpeAnYlTCrgO8D-Ie5eNSdGCAhuUUh8',
    appId: '1:458692017479:ios:963dfeef2e10d5b458a062',
    messagingSenderId: '458692017479',
    projectId: 'seefochat-25003',
    storageBucket: 'seefochat-25003.appspot.com',
    iosBundleId: 'com.clubchat.live.chat.clubchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvCpeAnYlTCrgO8D-Ie5eNSdGCAhuUUh8',
    appId: '1:458692017479:ios:ada5c1d09201723e58a062',
    messagingSenderId: '458692017479',
    projectId: 'seefochat-25003',
    storageBucket: 'seefochat-25003.appspot.com',
    iosBundleId: 'com.clubchat.live.chat.clubchat.RunnerTests',
  );
}
