// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb4oP4iFsqmSF-m28EJb_tlh6S_7syBlg',
    appId: '1:1050685348514:web:bfd95a53d59c16a55bd5fb',
    messagingSenderId: '1050685348514',
    projectId: 'clubchatapp-5d5ac',
    authDomain: 'clubchatapp-5d5ac.firebaseapp.com',
    storageBucket: 'clubchatapp-5d5ac.appspot.com',
    measurementId: 'G-PQZRQWVYNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCANFniAp9ch8AqV7kdHrLjUB9xG6Mml3g',
    appId: '1:1050685348514:android:4d7bf5158a7b07f45bd5fb',
    messagingSenderId: '1050685348514',
    projectId: 'clubchatapp-5d5ac',
    storageBucket: 'clubchatapp-5d5ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlpRpjpameZsv5k-skRyVmIwIP_GmyA0k',
    appId: '1:1050685348514:ios:8c041ded2706bdf95bd5fb',
    messagingSenderId: '1050685348514',
    projectId: 'clubchatapp-5d5ac',
    storageBucket: 'clubchatapp-5d5ac.appspot.com',
    iosBundleId: 'com.clubchat.live.chat.clubchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlpRpjpameZsv5k-skRyVmIwIP_GmyA0k',
    appId: '1:1050685348514:ios:84d1b2e4cda57b5e5bd5fb',
    messagingSenderId: '1050685348514',
    projectId: 'clubchatapp-5d5ac',
    storageBucket: 'clubchatapp-5d5ac.appspot.com',
    iosBundleId: 'com.clubchat.live.chat.clubchat.RunnerTests',
  );
}
