const Map<String,String> ar ={
  'about_us_title' : 'عن التطبيق',
  'about_us_version' : 'رقم النسخة',
  'about_us_update_version' : 'تحديث النسخة',
  'about_us_official_website' : 'الموقع الرسمي',
  'account_management_title' : 'إدارة الحساب',
  'add_post' : 'نشر',
  'add_post_msg' : 'تتم مراجعة مشاركتك من قبل أحد المشرفين لدينا وسيتم قبولها قريبا ',
  'add_photo_gallery' : 'معرض الصور',
  'add_camera' : 'كاميرا',
  'add_status_my_status' : 'حالتي',
  'add_status_share' : 'مشاركة',
  'add_status_msg' : 'تم تحديث الحالة بنجاح',
  'agreement_title' : 'اتفاقية الاستخدام',
  'agreement_user_agreement' : 'اتفاقية استخدام كلوب شات',
  'edit_language' : 'اللغة',
  'edit_arabic' : 'العربية',
  'edit_profile_title' : 'تعديل الملف الشخصي',
  'edit_profile_Cover_photo' : 'صورة الغلاف',
  'edit_profile_upload' : 'رفع',
  'edit_profile_basic_information' : 'معلومات اساسية',
  'edit_profile_user_name' : 'اسم المستخدم',
  'edit_profile_gender' : 'النوع',
  'edit_profile_male' : 'ذكر',
  'edit_profile_female' : 'انثى',
  'edit_profile_date_of_birth' : 'تاريخ الميلاد',
  'edit_profile_country' : 'البلد',
  'edit_profile_my_tags' : 'هواياتي',
  'edit_profile_update' : 'تحديث',
  'edit_profile_tag_msg' : 'تم تحديث هواياتك بنجاح',
  'edit_profile_user_name_title' : 'اسم المستخدم',
  'edit_profile_characters !' : 'الحد الاقصى 20 حرف !',
  'edit_profile_enter_user_name' : 'أدخل اسم المستخدم',
  'edit_profile_cancel' : 'الغاء',
  'edit_profile_edit' : 'تعديل',
  'edit_profile_photo_msg' : 'تم تحديث صورتك!',
  'edit_profile_Cover_msg' : 'تم تحديث الغلاف الخاص بك!',
  'followers_title' : 'المتابعون',
  'following_title' : "متابعة",
  'friends_title' : 'الاصدقاء',
  'home_party' : 'حفلة',
  'home_discover' : 'اكتشاف',
  'inner_report' : 'تقرير',
  'inner_block' : 'حظر',
  'inner_basic_information' : 'المعلومات الاساسية',
  'inner_room_gifts' : 'غرفة الهدايا',
  'inner_my_frames' : 'إطاراتي',
  'inner_cars_(Entries)' : 'السيارات (المدخلات)',
  'login_welcome_msg' : 'مرحبا بكم في كلوب شات !',
  'login_title' : 'الامر يتعلق بالمرح !',
  'login_privacy' : 'بنسجيلك في كلوب شات فانك توافق على ذلك',
  'login_policy' : 'سياسة كلوب شات',
  'login_and' : 'و',
  'login_services' : 'شروط استخدام كلوب شات',
  'mall_title' : 'المتجر',
  'mall_purchase' : 'شراء',
  'mall_msg' : 'آسف ليس لديك ما يكفي من الذهب!',
  'moments_recommend':'موصى يها',
  'moments_mine':'منشوراتي',
  'moments_follow':'متابعة',
  'moments_not_interested':'غير مهتم',
  'moments_report':'تقرير',
  'my_designs_days':'الايام:',
  'my_designs_use':'استحدام:',
  'my_level_wealth':'المساهمة :',
  'my_level_karizma':'الكاريرما :',
  'my_level_charging':'شحن :',
  'my_level_current_points':'النقاط الحالية',
  'my_level_next_level':'إلى المستوى التالي',
  'my_level_ways_to_level_up':'طرق الارتقاء بالمستوى ؟',
  'my_level_send_gift':'ارسل هدية لصديق في غرفة الدردشة',
  'my_level_gold_point':'1 ذهب = 1 نقطة',
  'my_level_receive':'تلقي هدية من صديق في غرفة الدردشة',
  'my_level_charge_your_gold':' اشحن الذهب الخاص بك !',
  'network_title':'تشخيص الشبكة',
  'network_start':'ابدا',
  'notification_moments':'اللحظات',
  'notification_profile':' الملف الشخصي',
  'notification_charging':'شحن',
  'notification_system':'النظام',
  'notification_announcement':'إعلان',
  'notification_setting_title':'الاشعارات',
  'notification_setting_private_chat':'الدردشة الخاصة',
  'notification_setting_new_followers':'المتابعين الجدد',
  'notification_setting_invitation_message':'رسالة دعوة',
  'notification_setting_moments_notification':'إشعار اللحظات',
  'post_title':'محتوى اللحظة',
  'post_label':'يرجى أن تكون ودية !',
  'post_msg':'تم إرسال تعليقك بنجاح!',
  'privacy_policy_title':'سياسة الخصوصية',
  'privacy_policy':'سياسة خصوصية كلوب شات',
  'profile_msg_copied':' تم نسخ رقم ID!',
  'profile_visitors':'الزوار',
  'profile_gold':'ذهب',
  'profile_diamond':'ماس',
  'profile_room':'غرفة',
  'profile_gifts':'الهدايا',
  'profile_level':'المستوى',
  'profile_my_posts':'منشوراتي',
  'profile_my_status':'حالتي',
  'profile_invite_friends':'دعوة الأصدقاء',
  'profile_medals':'الميداليات',
  'profile_contact_us':'اتصل بنا',
  'profile_terms_of_use':'شروط الاستخدام',
  'profile_account_settings':'إعدادات الحساب',
  'search_user':'مستخدم',
  'search_label_search':'البحث عن المستخدمين حسب ID / الاسم',
  'setting_title':'الاعدادات',
  'setting_language':'اللغة',
  'setting_notification':'الاشعارات',
  'setting_blocked_list':'قائمة المحظورين',
  'setting_identity_verification':'التحقق من الهوية',
  'setting_clear_cache':'مسح ذاكرة التخزين المؤقت',
  'setting_views':'مشاهدة',
  'taps_home':'الرئيسية',
  'taps_chats':'الدردشة',
  'taps_me':'انا',
  'add_post_label':'شارك برأيك على جدار اللحظات !',
  'gift_one_or_more_user':'مستخدم واحد أو أكثر',
  'gift_all_mic_users':'جميع مستخدمي الميكروفون',
  'gift_all_room_users':'جميع مستخدمي الغرفة',
  'gift_send_to_all_room_members':'إرسال إلى جميع أعضاء الغرفة',
  'gift_send':'ارسال',
  'menu_theme':'الخلفيات',
  'menu_music':' موسيقى',
  'menu_lucky_number':'رقم الحظ',
  'menu_dice':'كعب',
  'menu_lucky_bag':'حقيبة الحظ',
  'menu_settings':'الاعدادات',
  'room_info_room_name':'اسم الغرفة',
  'room_info_room_admin':'مشرف الغرفة',
  'room_info_room_country':'دولة الغرفة',
  'room_settings':'اعدادات الغرفة',
  'room_settings_room_title':'اسم الغرفة',
  'room_settings_update':'تحديث',
  'room_settings_hello':'رسالة الترحيب',
  'room_settings_room_password':'كلمة مرور الغرفة',
  'room_settings_room_admins':'مشرفين الغرفة',
  'room_settings_room_block_list':'قائمة الحظر',
  'chats_massage':'الرسائل',
  'chats_friends':'الاصدقاء',
  'chats_event_message':'اشعارات الانشطة',
  'chats_club_chat_service':'خدمة العملاء',
  'chats_system_massage':'رسائل النظام',
  'room_members': "أعضاء الغرفة",
  "log_out":"تسجيل الخروج",
  "logout_msg": "هل تريد تسجيل الخروج",
  "delete_account":"حذف الحساب",
  "delete_Account_msg":"هل تريد حذف الحساب",
  "change_local": "تغيير اللغة",
  "change_local_msg": "هل تريد تغيير لغة التطبيق",
  "login_phone_title": "قوم بالتسجيل برقم جوالك",
  'login_phone_hint': "اكتب رقمك مع كود الدولة",
  "send_btn": "أرسل",
  "verify_btn":"تأكيد",
  "verify_phone_hint": "أدخل كود التفعيل",
  "verify_phone_title": "تفعيل رقم الجوال الخاص بك",
  "room_close_keep": "حفظ",
  "room_close_exit": "خروج",
  'edit_ok' : 'موافق',
  'add_status_label_text' : '#شارك سيرتك الذاتية مع الأصدقاء!',
  'invite_invite_friends' : 'قم بدعوة أصدقائك إلى كلوب شات والاحتفال معا!',
  'invite_copy' : 'نسخ رابط الدعوة ',
  'inner_msg_followed' : 'لقد تابعت هذا المستخدم',
  'inner_msg_unfollowed' : 'لقد قمت بإلغاء متابعة هذا المستخدم',
  'inner_msg_no_room' : 'عذرا هذا المستخدم ليس لديه غرفة',
  'inner_msg_not_any_room' : 'عذرا هذا المستخدم ليس في أي غرفة',
  'chat_search_friend' : 'ابحث عن اصدقائك عن طريق المعرف / الاسم',
  'remote_app_msg' : 'لقد أبلغت عن هذا المستخدم!',
  'remote_app_msg_error ' : 'خطأ! حدث خطأ ما',
  'remote_app_msg_blocked' : 'لقد قمت بحظر هذا المستخدم !',
  'remote_chat_msg_failed' : 'فشل فتح الغرفة ، يرجى الاتصال بالدعم',
  'remote_design_msg_design' : 'تعيين التصميم إلى الوضع الافتراضي',
  'contact_Us_title' : 'اتصل بنا',
  'contact_Us_club_chat' : 'نحن في كلوب شات يسعدنا مساعدتك وتلبية طلباتك وجعل تجربة استخدامك للتطبيق تجربة ممتعه لذا لا تتاخر من التواصل معنا اذا واجهتك اي مشكلة , نحن دائما في خدمتك 24 ساعة طوال ايام الاسبوع ',
  'contact_Us_social_media' : 'كما سيسعدنا متابعتك لنا على منصات التواصل ',
  'verification_title' : 'تحقق الهوية',
  'verification_id_card' : 'يرجى إرفاق صورة من بطاقة الهوية الخاصة بك',
  'verification_id_face' : 'صورة وجهة بطاقة الهوية',
  'verification_id_back' : 'صورة ظهر بطاقة الهوية',
  'verification_verify' : 'تاكيد',
  'clear_cash_msg': 'تم حذف الكاش بنجاح',
  'chats_update_data_msg' : 'تم التحديث بنجاح',
  'event_message_title' : 'رسائل التنبيهات',
  'customer_service_title' : 'خدمة العملاء',



};