const Map<String, String> ar = {
  'about_us_title': 'عن التطبيق',
  'about_us_version': 'رقم النسخة',
  'about_us_update_version': 'تحديث النسخة',
  'about_us_official_website': 'الموقع الرسمي',
  'account_management_title': 'إدارة الحساب',
  'add_post': 'نشر',
  'add_post_msg': 'تتم مراجعة مشاركتك من قبل أحد المشرفين لدينا وسيتم قبولها قريبا',
  'add_photo_gallery': 'معرض الصور',
  'add_camera': 'كاميرا',
  'add_status_my_status': 'حالتي',
  'add_status_share': 'مشاركة',
  'add_status_msg': 'تم تحديث الحالة بنجاح',
  'agreement_title': 'إتفاقية الأستخدام',
  'agreement_user_agreement': 'إتفاقية إستخدام كلوب شات',
  'edit_language': 'اللغة',
  'edit_arabic': 'العربية',
  'edit_profile_title': 'تعديل الملف الشخصي',
  'edit_profile_Cover_photo': 'صورة الغلاف',
  'edit_profile_upload': 'رفع',
  'edit_profile_basic_information': 'معلومات أساسية',
  'edit_profile_user_name': 'إسم المستخدم',
  'edit_profile_gender': 'النوع',
  'edit_profile_male': 'ذكر',
  'edit_profile_female': 'أنثى',
  'edit_profile_date_of_birth': 'تاريخ الميلاد',
  'edit_profile_country': 'البلد',
  'edit_profile_my_tags': 'هواياتي',
  'edit_profile_update': 'تحديث',
  'edit_profile_tag_msg': 'تم تحديث هواياتك بنجاح',
  'edit_profile_user_name_title': 'إسم المستخدم',
  'edit_profile_characters !': 'الحد الاقصى 20 حرف !',
  'edit_profile_enter_user_name': 'أدخل إسم المستخدم',
  'edit_profile_cancel': 'إلغاء',
  'edit_profile_edit': 'تعديل',
  'edit_profile_photo_msg': 'تم تحديث صورتك!',
  'edit_profile_Cover_msg': 'تم تحديث الغلاف الخاص بك!',
  'followers_title': 'المتابعون',
  'following_title': "متابعة",
  'friends_title': 'الأصدقاء',
  'home_party': 'حفلة',
  'home_discover': 'إكتشاف',
  'inner_report': 'تقرير',
  'inner_block': 'حظر',
  'inner_basic_information': 'المعلومات الأساسية',
  'inner_room_gifts': 'غرفة الهدايا',
  'inner_my_frames': 'إطاراتي',
  'inner_cars_(Entries)': 'السيارات (المدخلات)',
  'login_welcome_msg': 'مرحبا بكم في كلوب شات !',
  'login_title': 'الأمر يتعلق بالمرح !',
  'login_privacy': 'بتسجيلك في كلوب شات فانك توافق على ذلك',
  'login_policy': 'سياسة كلوب شات',
  'login_and': 'و',
  'login_services': 'شروط استخدام كلوب شات',
  'mall_title': 'المتجر',
  'mall_purchase': 'شراء',
  'mall_msg': 'آسف ليس لديك ما يكفي من الذهب!',
  'moments_recommend': 'موصى بها',
  'moments_mine': 'منشوراتي',
  'moments_follow': 'متابعة',
  'moments_not_interested': 'غير مهتم',
  'moments_report': 'تقرير',
  'my_designs_days': 'الأيام:',
  'my_designs_use': 'إستحدام:',
  'my_level_wealth': 'المساهمة :',
  'my_level_karizma': 'الكاريرما :',
  'my_level_charging': 'شحن :',
  'my_level_current_points': 'النقاط الحالية',
  'my_level_next_level': 'إلى المستوى التالي',
  'my_level_ways_to_level_up': 'طرق الأرتقاء بالمستوى ؟',
  'my_level_send_gift': 'أرسل هدية لصديق في غرفة الدردشة',
  'my_level_gold_point': '1 ذهب = 1 نقطة',
  'my_level_receive': 'تلقي هدية من صديق في غرفة الدردشة',
  'my_level_charge_your_gold': ' إشحن الذهب الخاص بك !',
  'network_title': 'تشخيص الشبكة',
  'network_start': 'إبدا',
  'notification_moments': 'اللحظات',
  'notification_profile': ' الملف الشخصي',
  'notification_charging': 'شحن',
  'notification_system': 'النظام',
  'notification_announcement': 'إعلان',
  'notification_setting_title': 'الإشعارات',
  'notification_setting_private_chat': 'الدردشة الخاصة',
  'notification_setting_new_followers': 'المتابعين الجدد',
  'notification_setting_invitation_message': 'رسالة الدعوة',
  'notification_setting_moments_notification': 'إشعار اللحظات',
  'post_title': 'محتوى اللحظة',
  'post_label': 'يرجى أن تكون ودية !',
  'post_msg': 'تم إرسال تعليقك بنجاح!',
  'privacy_policy_title': 'سياسة الخصوصية',
  'privacy_policy': 'سياسة خصوصية كلوب شات',
  'profile_msg_copied': ' تم نسخ رقم ID!',
  'profile_visitors': 'الزوار',
  'profile_gold': 'ذهب',
  'profile_diamond': 'ماس',
  'profile_room': 'غرفة',
  'profile_gifts': 'الهدايا',
  'profile_level': 'المستوى',
  'profile_my_posts': 'منشوراتي',
  'profile_my_status': 'حالتي',
  'profile_invite_friends': 'دعوة الأصدقاء',
  'profile_medals': 'الميداليات',
  'profile_contact_us': 'اتصل بنا',
  'profile_terms_of_use': 'شروط الإستخدام ',
  'profile_account_settings': 'إعدادات الحساب',
  'search_user': 'مستخدم',
  'search_label_search': 'البحث عن المستخدمين حسب ID / الإسم',
  'setting_title': 'الإعدادات ',
  'setting_language': 'اللغة',
  'setting_notification': 'الإشعارات',
  'setting_blocked_list': 'قائمة المحظورين',
  'setting_identity_verification': 'التحقق من الهوية',
  'setting_clear_cache': 'مسح ذاكرة التخزين المؤقت',
  'setting_views': 'مشاهدة',
  'taps_home': 'الرئيسية',
  'taps_chats': 'الدردشة',
  'taps_me': 'أنا',
  'add_post_label': 'شارك برأيك على جدار اللحظات !',
  'gift_one_or_more_user': 'مستخدم واحد أو أكثر',
  'gift_all_mic_users': 'جميع مستخدمي الميكروفون',
  'gift_all_room_users': 'جميع مستخدمي الغرفة',
  'gift_send_to_all_room_members': 'إرسال إلى جميع أعضاء الغرفة',
  'gift_send': 'إرسال',
  'menu_theme': 'الخلفيات',
  'menu_music': ' موسيقى',
  'menu_lucky_number': 'رقم الحظ',
  'menu_dice': 'كعب',
  'menu_lucky_bag': 'حقيبة الحظ',
  'menu_settings': 'الاعدادات',
  'room_info_room_name': 'إسم الغرفة',
  'room_info_room_admin': 'مشرف الغرفة',
  'room_info_room_country': 'دولة الغرفة',
  'room_settings': 'إعدادات الغرفة',
  'room_settings_room_title': 'إسم الغرفة',
  'room_settings_update': 'تحديث',
  'room_settings_hello': 'رسالة الترحيب',
  'room_settings_room_password': 'كلمة مرور الغرفة',
  'room_settings_room_admins': 'مشرفين الغرفة',
  'room_settings_room_block_list': 'قائمة الحظر',
  'chats_massage': 'الرسائل',
  'chats_friends': 'الأصدقاء',
  'chats_event_message': 'إشعارات الانشطة',
  'chats_club_chat_service': 'خدمة العملاء',
  'chats_system_massage': 'رسائل النظام',
  'room_members': "أعضاء الغرفة",
  "log_out": "تسجيل الخروج",
  "logout_msg": "هل تريد تسجيل الخروج",
  "delete_account": "حذف الحساب",
  "delete_Account_msg": "هل تريد حذف الحساب",
  "change_local": "تغيير اللغة",
  "change_local_msg": "هل تريد تغيير لغة التطبيق",
  "login_phone_title": "قوم بالتسجيل برقم جوالك",
  'login_phone_hint': "إكتب رقمك مع كود الدولة",
  "send_btn": "أرسل",
  "verify_btn": "تأكيد",
  "verify_phone_hint": "أدخل كود التفعيل",
  "verify_phone_title": "تفعيل رقم الجوال الخاص بك",
  "room_close_keep": "حفظ",
  "room_close_exit": "خروج",
  'edit_ok': 'موافق',
  'add_status_label_text': '#شارك سيرتك الذاتية مع الأصدقاء!',
  'invite_invite_friends': 'قم بدعوة أصدقائك إلى كلوب شات والاحتفال معا!',
  'invite_copy': 'نسخ رابط الدعوة ',
  'inner_msg_followed': 'لقد تابعت هذا المستخدم',
  'inner_msg_unfollowed': 'لقد قمت بإلغاء متابعة هذا المستخدم',
  'inner_msg_no_room': 'عذرا هذا المستخدم ليس لديه غرفة',
  'inner_msg_not_any_room': 'عذرا هذا المستخدم ليس في أي غرفة',
  'chat_search_friend': ' إبحث عن اصدقائك عن طريق المعرف  / الإسم ',
  'remote_app_msg': 'لقد أبلغت عن هذا المستخدم!',
  'remote_app_msg_error ': 'خطأ! حدث خطأ ما',
  'remote_app_msg_blocked': 'لقد قمت بحظر هذا المستخدم !',
  'remote_chat_msg_failed': 'فشل فتح الغرفة ، يرجى الاتصال بالدعم',
  'remote_design_msg_design': 'تعيين التصميم إلى الوضع الافتراضي',
  'contact_Us_title': 'اتصل بنا',
  'contact_Us_club_chat': 'نحن في كلوب شات يسعدنا مساعدتك وتلبية طلباتك وجعل تجربة إستخدامك للتطبيق تجربة ممتعة لذا لا تتاخر من التواصل معنا إذا واجهتك أي مشكلة , نحن دائما في خدمتك 24 ساعة طوال ايام الاسبوع ',
  'contact_Us_social_media': 'كما سيسعدنا متابعتك لنا على منصات التواصل ',
  'verification_title': 'تحقق الهوية',
  'verification_id_card': 'يرجى إرفاق صورة من بطاقة الهوية الخاصة بك',
  'verification_id_face': 'صورة وجهة بطاقة الهوية',
  'verification_id_back': 'صورة ظهر بطاقة الهوية',
  'verification_verify': 'تأكيد',
  'clear_cash_msg': 'تم حذف الكاش بنجاح',
  'chats_update_data_msg': 'تم التحديث بنجاح',
  'event_message_title': 'رسائل التنبيهات',
  'customer_service_title': 'خدمة العملاء',
  'delete_chat': 'حذف المحادثة',
  'block_user': 'حظر',
  'user_app_blocked_title': 'لقد تم حظرك!',
  'user_app_blocked_msg': 'عفوا لا يمكنك دخول التطبيق حيث أنه تم حظرك من إستخدام خدمات التطبيق يمكتك التواصل مع الإدارة لمزيد من التفاصيل',
  'recharge_gold': 'شحن رصيد الذهب',
  "diamond_exchange": " إستبدال رصيد الماس",
  "diamond_exchange_inp_hint": " إكتب قيمة التحويل",
  "diamond_exchange_note": "أقل قيمة للتحويل هي 100 ماسة",
  "diamond_exchange_rules": "تعليمات تحويل الماس الي ذهب",
  "wallet_diamond_rule1": "الهدايا التي تحصل عليها يتم تحويلها تلقائيا إلي ماس بالنسب المحددة والمتفق عليها",
  "wallet_diamond_rule2": "نسبة تحويل الماس إلي ذهب هي ",
  "exchanged_gold": " قيمة الذهب المحول : ",
  "exchange_btn": "تحويل الي ذهب",
  "details": "تفاصيل",
  "exchange_failed": "لا يمكن تحويل الماس إلا إذا كانت القيمة 100 ماسة أو أكثر",
  "charging_details": "تفاصيل الشحن",
  "exchange_failed2": "عفوا رصيدك من الماس لا يسمح",
  "edit_profile_user_gender": "تعديل نوع المستخدم",
  "vip": "الأرستقراطية",
  "vip_privileges": " أمتيازات الأرستقراطية ",
  "Vip_package": "حزمة الأرستقراطية",
  "car": "سيارة",
  "medal": "شارة",
  "special_msg":"رسائل مميزة",
  "entering_effect": "تأثير دخول",
  "login_time":"إخفاء تاريخ التسجيل",
  "stop_track": "منع التتبع",
  "no_kick": "منع الطرد",
  "use_mic": "الصعود علي المايك",
  "mic_closed_msg": "عفوا هذا المايك مغلق",
  "un_use_mic": "مغادرة من المايك",
  "mute": "كتم الصوت",
  "lock_mic": "غلق المايك",
  "lock_all_mics": "غلق كل المايكات",
  "unlock_mic": "فتح المايك",
  "unlock_all_mic": "فتح كل المايكات",
  'remove_from_mic': "حذف من المايك",
  'chat_error': 'خطأ',
  'chat_loading': ' جاري التحميل',
  'inner_nothing': 'لا شيء هنا',
  'inner_nothing_update': 'لا شيء هنا، قم بتحديث سيرتك الذاتية',
  'login_verify_phone': 'آسف لا يمكننا التحقق من الهاتف الآن!',
  'login_code_msg': 'تم إرسال رمز التحقق بنجاح',
  'network_msg': 'كافة خدمات الشبكة تعمل كما هو متوقع',
  'splash_party':'احتفل كلما استطعت',
  'musics2_model_add_music': 'إضافه موسيقي',
  'musics_model_my_music':'الموسيقي',
  'agency_charge_title':'شحن رصيد العضو',
  'agency_charge_operation_title' : 'عمليات الشحن',
  'agency_charge_search' : 'بحث',
  'agency_charge_charge' : 'شحن',
  'agency_charge_user_data' : 'بيانات المستخدم',
  'join_host_title' : 'طلب الانضمام للوكالة',
  'join_host_request' : 'إرسال طلب الانضمام',
  'join_host_data' : 'بيانات الوكالة',
  'agency_income_title' : 'دخل المضيف ',
  'agency_income_target' : 'الهدف',
  'agency_income_work_hour' : 'عدد ساعات العمل',
  'agency_income_hour' : 'ساعة : ',
  'agency_income_day' : 'يوم : ',
  'agency_income_work_points' : 'عدد النقاط الحالية',
  'agency_income_next_target' : 'متبقى على تحقيق الهدف التالي.',
  'agency_income_next_achieve_target' : 'متبقى لتحقيق الهدف التالي',
'block_msg_unblocked' : 'لقد قمت بإلغاء حظر هذا المستخدم!',
  'chat_hint_text_form' : 'اكتب شيئاً ...',
  'chat_no_resents' : 'لا يوجد حالياً',
  'room_close_mic' : 'آسف هذا الميكروفون مغلق',
  'room_msg': "إدارة كلوب شات تتمني لكم تقضية أوقات ممتعة داخل منصتها وتؤكد علي أهمية الحفاظ علي أداب وضوابط التواصل المحترم بين جميع الأعضاء وتجنب المضايقات كما يحذر المواضيع الجنسية والعرقية والدينية ",
  "notice" : "ملاحظة : ",
  "user_enter_message" : "مرحبا ...",
  "host_agency_search": "البحث بمعرف الوكالة",
  "request_process" : "يتم معالجة طلبك الأن",
  "agency_members_title":"أعضاء الوكالة",
  "choose_receiver" : "يجب تحديد مستلم الهدية أولا",
  "choose_gift": "برجاء اختيار الهدية",
  "daily": "يومي",
  "weekly":"أسبوعي",
  "monthly":"شهري",
  "app_rank": "كاس كلوب شات",
  "room_remove_mic": "عفوا لقد أنزلك الأدمن من علي المايك",
  "music_error_permissions": "لا يمكن تحميل ملفات الموسيقي بدون إعطاء إذن الوصول الي الملفات",
  "unmute": "تشغيل الصوت",
  "room_settings_room_subject": "نوع الغرفة",
  "room_settings_room_img": "صورة الغرفة",
  "room_password_label":"كلمة مرور الغرفة",
  "room_password_wrong": "كلمة مرور غير صحيحة",
  "show_profile": "عرض المستخدم",
  "admin_mic_alert": "عفوا! مايك خاص بالمديرين فقط",
  "should_be_on_mic": "عفوا يجب ان تكون مستخدم مايك !",
  "add_admin": "أدمن",
  "add_admin_title": "إضافة مدير للغرفة",
  "admin_added": "تم تعيين مدير جديد",
  "remove_btn": "حذف",
  "admin_deleted": "تم حذف المدير",
  "room_save_dialog_title": "إلفاء حفظ الغرفة",
  "room_save_dialog_msg": "هل تريد إلغاء إحتقاظ الغرفة"



};