const Map<String,String> en ={
  'about_us_title' : 'About Us',
  'about_us_version' : 'Version',
  'about_us_update_version' : 'Update Version',
  'about_us_official_website' : 'Official Website',
  'account_management_title' : 'Account Management',
  'add_post' : 'Post',
  'add_post_msg' : 'Your post is being reviewed by one of our admins and it will be accepted very soon',
  'add_photo_gallery' : 'Photo Gallery',
  'add_camera' : 'Camera',
  'add_status_my_status' : 'My Status',
  'add_status_share' : 'Share',
  'add_status_msg' : 'Status Updated Successfully',
  'agreement_title' : 'Agreement',
  'agreement_user_agreement' : 'club chat User Agreement',
  'edit_language' : 'Edit Language',
  'edit_arabic' : 'Arabic',
  'edit_profile_title' : 'Edit Profile',
  'edit_profile_Cover_photo' : 'Cover Photo',
  'edit_profile_upload' : 'Upload',
  'edit_profile_basic_information' : 'Basic Information',
  'edit_profile_user_name' : 'User Name',
  'edit_profile_gender' : 'Gender',
  'edit_profile_male' : 'Male',
  'edit_profile_female' : 'Female',
  'edit_profile_date_of_birth' : 'Date of Birth',
  'edit_profile_country' : 'Country',
  'edit_profile_my_tags' : 'My Tags',
  'edit_profile_update' : 'Update',
  'edit_profile_tag_msg' : 'Tags Updated Successfully',
  'edit_profile_user_name_title' : 'User Name',
  'edit_profile_characters !' : 'Up to 20 Characters !',
  'edit_profile_enter_user_name' : 'Enter User Name',
  'edit_profile_cancel' : 'CANCEL',
  'edit_profile_edit' : 'Edit',
  'edit_profile_photo_msg' : 'Your photo has been updated!',
  'edit_profile_Cover_msg' : 'Your Cover has been updated!',
  'followers_title' : 'Followers',
  'following_title' : 'Following',
  'friends_title' : 'Friends',
  'home_party' : 'Party',
  'home_discover' : 'Discover',
  'inner_report' : 'Report',
  'inner_block' : 'Block',
  'inner_basic_information' : 'Basic Information',
  'inner_room_gifts' : 'Room Gifts',
  'inner_my_frames' : 'My Frames',
  'inner_cars_(Entries)' : 'Cars (Entries)',
  'login_welcome_msg' : 'Welcome To Club Chat !',
  'login_title' : 'Welcome To Club Chat !',
  'login_privacy' : 'By signing in ClubChat you agree to',
  'login_policy' : 'ClubChat Policy',
  'login_and' : 'and',
  'login_services' : 'ClubChat Terms Services',
  'mall_title' : 'Mall',
  'mall_purchase' : 'Purchase',
  'mall_msg' : 'Sorry you do not have enough gold !',
  'moments_recommend':'Recommend',
  'moments_mine':'Mine',
  'moments_follow':'Follow',
  'moments_not_interested':'Not Interested',
  'moments_report':'report',
  'my_designs_days':'Days:',
  'my_designs_use':'Use:',
  'my_level_wealth':'Wealth:',
  'my_level_karizma':'Karizma:',
  'my_level_charging':'Charging:',
  'my_level_current_points':'The Current Points',
  'my_level_next_level':'To The Next Level',
  'my_level_ways_to_level_up':'Ways To Level Up ?',
  'my_level_send_gift':'Send Gift to friend in Chat Room',
  'my_level_gold_point':'1 Gold = 1 Point',
  'my_level_receive':'Receive Gift to Friend in Chat Room',
  'my_level_charge_your_gold':'Charge Your Gold !',
  'network_title':'Network Diagnosis',
  'network_start':'Start',
  'notification_moments':'Moments',
  'notification_profile':'Profile',
  'notification_charging':'Charging',
  'notification_system':'System',
  'notification_announcement':'Announcement',
  'notification_setting_title':'Notification',
  'notification_setting_private_chat':'Private Chat',
  'notification_setting_new_followers':'New followers',
  'notification_setting_invitation_message':'Invitation Message',
  'notification_setting_moments_notification':'Moments Notification',
  'post_title':'Moment Content',
  'post_label':'Please be Friendly !',
  'post_msg':'Your comment Sent Successfully!',
  'privacy_policy_title':'Privacy Policy',
  'privacy_policy':'club chat Privacy Policy',
  'profile_msg_copied':'User ID Copied !',
  'profile_visitors':'Visitors',
  'profile_gold':'Gold',
  'profile_diamond':'Diamond',
  'profile_room':'Room',
  'profile_gifts':'Gifts',
  'profile_level':'Level',
  'profile_my_posts':'My Posts',
  'profile_my_status':'My Status',
  'profile_invite_friends':'Invite Friends',
  'profile_medals':'Medals',
  'profile_contact_us':'Contact Us',
  'profile_terms_of_use':'Terms of Use',
  'profile_account_settings':'Account Settings',
  'search_user':'User',
  'search_label_search':'Search in Users by ID / Name',
  'setting_title':'Setting',
  'setting_language':'Language',
  'setting_notification':'Notification',
  'setting_blocked_list':'Blocked List',
  'setting_identity_verification':'Identity Verification',
  'setting_clear_cache':'Clear Cache',
  'setting_views':'Views',
  'taps_home':'Home',
  'taps_chats':'Chats',
  'taps_me':'Me',
  'add_post_label':'Share Your Thoughts on Moments wall !',
  'gift_one_or_more_user':'one or more user',
  'gift_all_mic_users':'All Mic Users',
  'gift_all_room_users':'All Room Users',
  'gift_send_to_all_room_members':'Send to All Room Members',
  'gift_send':'Send',
  'menu_theme':'Theme',
  'menu_music':'Music',
  'menu_lucky_number':'Lucky Number',
  'menu_dice':'Dice',
  'menu_lucky_bag':'Lucky Bag',
  'menu_settings':'Settings',
  'room_info_room_name':'Room Name',
  'room_info_room_admin':'Room Admin',
  'room_info_room_country':'Room Country',
  'room_settings':'Room Settings',
  'room_settings_room_title':'Room Title',
  'room_settings_update':'update',
  'room_settings_hello':'Room Hello Text',
  'room_settings_room_password':'Room Password',
  'room_settings_room_admins':'Room Admins',
  'room_settings_room_block_list':'Room Block List',
  'chats_massage':'Massage',
  'chats_friends':'Friends',
  'chats_event_message':'Event Message',
  'chats_club_chat_service':'Customer Service',
  'chats_system_massage':'System Message',
  'room_members': 'Room Members',
   'log_out': "LogOut",
  "logout_msg": "Do You really want to LogOut ?",
  "delete_account":"Delete Account",
  "delete_Account_msg":"Do You really want to Delete Account ?",
  "change_local": " Change Language",
  "change_local_msg": "Do You really want to Change App Language ?",
  "login_phone_title": "Login With Your Phone Number",
  'login_phone_hint': "Enter Phone Number With Country Code",
  "send_btn": "Send",
  "verify_btn":"Verify",
  "verify_phone_hint": "Enter Verification Code ",
  "verify_phone_title": "Verify Phone Number",
  "room_close_keep": "Keep",
  "room_close_exit": "Exit",
  'edit_ok' : 'OK',
  'add_status_label_text' : '#Share Your Bio With Friends!',
  'invite_invite_friends' : 'Invite Your Friends to club chat and party together!',
  'invite_copy' : 'Copy the invitation link ',
  'inner_msg_followed' : 'you have followed this user',
  'inner_msg_unfollowed' : 'you have unfollowed this user',
  'inner_msg_no_room' : 'Sorry this user has no room',
  'inner_msg_not_any_room' : 'Sorry this user has no room',
  'chat_search_friend' : 'Search in Your Friend by ID / Name',
  'remote_app_msg' : 'You have reported this user !',
  'remote_app_msg_error' : 'Error! Something went wrong',
  'remote_app_msg_blocked' : 'You have blocked this user !',
  'remote_chat_msg_failed' : 'Failed to open room , please contact support',
  'remote_design_msg_design' : 'Design set to default',
  'contact_Us_title' : 'Contact Us',
  'contact_Us_club_chat' : 'We at Club Chat are happy to help you, fulfill your requests and make your experience of using the application a fun experience, so do not delay in contacting us if you face any problem, we are always at your service 24 hours a day, 7 days a week ',
  'contact_Us_social_media' : 'We will also be happy to follow you on social media platforms',
  'verification_title' : 'Verification',
  'verification_id_card' : 'Please attach a copy of your ID card',
  'verification_id_face' : 'A photo of the face of the ID card',
  'verification_id_back' : 'A photo of the back of the ID card',
  'verification_verify' : 'Verify',
  'clear_cash_msg': 'Cash Cleared Successfully',
  'chats_update_data_msg' : 'Data Update Successfully',
  'event_message_title' : 'Event Message',
  'customer_service_title' : 'Customer Service',
  'delete_chat' : 'Delete Chat',
  'block_user' : 'Block User',
  'user_app_blocked_title': "You are Blocked !",
  "user_app_blocked_msg":"Sorry you can not enter the app as you are blocked from using our app services , please contact support for further actions ",
  "recharge_gold": "Recharge Gold Balance",
  "diamond_exchange": "Diamond Exchange",
  "diamond_exchange_inp_hint": "Enter Exchange Value",
  "diamond_exchange_note": "* At least exchange of 100 diamonds",
  "diamond_exchange_rules": "Diamond Exchange Rules",
  "wallet_diamond_rule1": "The gifts you receive will be automatically converted into diamonds",
  "wallet_diamond_rule2": "the ratio of diamond to golds is ",
  "exchanged_gold": "The Exchanged Gold: ",
  "exchange_btn": "Exchange To Gold",
  "details": "Details",
  "exchange_failed": "At least exchange of 100 diamonds",
  "charging_details": "Charging Details",
  "exchange_failed2": "No Balance !",
  "edit_profile_user_gender": "Edit User Gender",
  "vip": "VIP",
  "vip_privileges": "vip privileges",
  "Vip_package": "Vip Package",
  "car": "Car",
  "medal": "Medal",
  "special_msg": "Special Messages",
  "entering_effect": "Entering effects",
  "login_time":"Hide First Login",
  "stop_track": "No Track",
  "no_kick": "No Kick out",
  "use_mic": "Use Mic",
  "mic_closed_msg": "Sorry this mic is closed !",
  "un_use_mic": "unUse Mic  ",
  "mute": "Mute Mic",
  "lock_mic": "Lock Mic",
  "lock_all_mics": "Lock All Mics ",
  "unlock_mic": "unLock Mic",
  "unlock_all_mic": "unLock All Mics",
  'remove_from_mic': "Remove From Mic ",
  'chat_error': 'Error',
  'chat_loading': 'Loading',
  'inner_nothing': 'Nothing here',
  'inner_nothing_update': 'Nothing here , update your bio',
  'login_verify_phone': 'sorry we can not verify phone right now !',
  'login_code_msg': 'code sent successfully',
  'network_msg': 'All Network Services is working as expected',
  'splash_party':'Party whenever you can',

};