const Map<String,String> en ={
  'about_us_title' : 'About Us',
  'about_us_version' : 'Version',
  'about_us_update_version' : 'Update Version',
  'about_us_official_website' : 'Official Website',
  'account_management_title' : 'Account Management',
  'add_post' : 'Post',
  'add_post_msg' : 'Your post is being reviewed by one of our admins and it will be accepted very soon',
  'add_photo_gallery' : 'Photo Gallery',
  'add_camera' : 'Camera',
  'add_status_my_status' : 'My Status',
  'add_status_share' : 'Share',
  'add_status_msg' : 'Status Updated Successfully',
  'agreement_title' : 'Agreement',
  'agreement_user_agreement' : 'club chat User Agreement',
  'edit_language' : 'Edit Language',
  'edit_arabic' : 'Arabic',
  'edit_profile_title' : 'Edit Profile',
  'edit_profile_Cover_photo' : 'Cover Photo',
  'edit_profile_upload' : 'Upload',
  'edit_profile_basic_information' : 'Basic Information',
  'edit_profile_user_name' : 'User Name',
  'edit_profile_gender' : 'Gender',
  'edit_profile_male' : 'Male',
  'edit_profile_female' : 'Female',
  'edit_profile_date_of_birth' : 'Date of Birth',
  'edit_profile_country' : 'Country',
  'edit_profile_my_tags' : 'My Tags',
  'edit_profile_update' : 'Update',
  'edit_profile_tag_msg' : 'Tags Updated Successfully',
  'edit_profile_user_name_title' : 'User Name',
  'edit_profile_characters !' : 'Up to 20 Characters !',
  'edit_profile_enter_user_name' : 'Enter User Name',
  'edit_profile_cancel' : 'CANCEL',
  'edit_profile_edit' : 'Edit',
  'edit_profile_photo_msg' : 'Your photo has been updated!',
  'edit_profile_Cover_msg' : 'Your Cover has been updated!',
  'followers_title' : 'Followers',
  'following_title' : 'Following',
  'friends_title' : 'Friends',
  'home_party' : 'Party',
  'home_discover' : 'Discover',
  'inner_report' : 'Report',
  'inner_block' : 'Block',
  'inner_basic_information' : 'Basic Information',
  'inner_room_gifts' : 'Room Gifts',
  'inner_my_frames' : 'My Frames',
  'inner_cars_(Entries)' : 'Cars (Entries)',
  'login_welcome_msg' : 'Welcome To Club Chat !',
  'login_title' : 'Welcome To Club Chat !',
  'login_privacy' : 'By signing in ClubChat you agree to',
  'login_policy' : 'ClubChat Policy',
  'login_and' : 'and',
  'login_services' : 'ClubChat Terms Services',
  'mall_title' : 'Mall',
  'mall_purchase' : 'Purchase',
  'mall_msg' : 'Sorry you do not have enough gold !',
  'moments_recommend':'Recommend',
  'moments_mine':'Mine',
  'moments_follow':'Follow',
  'moments_not_interested':'Not Interested',
  'moments_report':'report',
  'my_designs_days':'Days:',
  'my_designs_use':'Use:',
  'my_level_wealth':'Wealth:',
  'my_level_karizma':'Karizma:',
  'my_level_charging':'Charging:',
  'my_level_current_points':'The Current Points',
  'my_level_next_level':'To The Next Level',
  'my_level_ways_to_level_up':'Ways To Level Up ?',
  'my_level_send_gift':'Send Gift to friend in Chat Room',
  'my_level_gold_point':'1 Gold = 1 Point',
  'my_level_receive':'Receive Gift to Friend in Chat Room',
  'my_level_charge_your_gold':'Charge Your Gold !',
  'network_title':'Network Diagnosis',
  'network_start':'Start',
  'notification_moments':'Moments',
  'notification_profile':'Profile',
  'notification_charging':'Charging',
  'notification_system':'System',
  'notification_announcement':'Announcement',
  'notification_setting_title':'Notification',
  'notification_setting_private_chat':'Private Chat',
  'notification_setting_new_followers':'New followers',
  'notification_setting_moments_notification':'Moments Notification',









};